### ISSUE TITLE
Updating timestamp when no other changes are made

### ISSUE THREAD

**Issue by mrjones2014** [ibhagwan/ts-vimdoc.nvim#1]
Example: https://github.com/mrjones2014/legendary.nvim/pull/337

There are no actual changes to the docs, but it still updates the timestamp. I seem to remember this being something that was fixed a while back?

**Comment by ibhagwan** [comment]
Looking at https://github.com/mrjones2014/legendary.nvim/commits/master I can see commits that don't generate a new vimdoc, is this specific to this commit or every commit? Nothing was changed in the code, the only change recently was to update a deprecated treesitter call.

**Comment by mrjones2014** [comment]
Actually you know what, I changed some nerdfont icons to the non-deprecated equivalents. Those probably generated a diff but GitHub didn’t see the difference so it appeared in the PR as though there was no diff.

**Comment by ibhagwan** [comment]
> Actually you know what, I changed some nerdfont icons to the non-deprecated equivalents. Those probably generated a diff but GitHub didn’t see the difference so it appeared in the PR as though there was no diff.

Ty for the update @mrjones2014!
