### ISSUE TITLE
Untracked file

### ISSUE THREAD

**Issue by hinell** [ibhagwan/ts-vimdoc.nvim#3]
https://github.com/ibhagwan/ts-vimdoc.nvim/blob/8ecfc3c2a4d73dba8b8239f1c13a72886892e774/lua/ts-vimdoc/parser.lua#L38-L47
```bash
Error detected while processing command line:
E5108: Error executing lua .../share/nvim/lazy/ts-vimdoc.nvim/lua/ts-vimdoc/parser.lua:50: field 'day' missing in date table
stack traceback:
        [C]: in function 'time'
        .../share/nvim/lazy/ts-vimdoc.nvim/lua/ts-vimdoc/parser.lua:50: in function 'header_line'
        .../share/nvim/lazy/ts-vimdoc.nvim/lua/ts-vimdoc/parser.lua:25: in function 'parse'
        ...al/share/nvim/lazy/ts-vimdoc.nvim/lua/ts-vimdoc/init.lua:21: in function 'docgen'
        [string ":lua"]:1: in main chunk
```

Hi. Currently, if an input file is untracked by git (e.g. added for the first time) , it throws the above error. 

Can we fallback to the current date in case of empty result?

Thanks.

**Comment by ohadkor** [comment]
> Can we fallback to the current date in case of empty result?

That would mean every run would modify the header date, wouldn’t it be better to fallback to the file system modify date?

**Comment by ibhagwan** [comment]
> Can we fallback to the current date in case of empty result?

I’ll take a look at the best solution for this.

**Comment by ibhagwan** [comment]
> Can we fallback to the current date in case of empty result?

Turns out this was already the coded logic for this but git wasn't returning an error code when the file wasn't tracked, it was returning an empty string instead.

Fixed in https://github.com/ibhagwan/ts-vimdoc.nvim/commit/8d77eb5749b54344942ff180c9c7a4efd8a18451
